### PR TITLE
[mellanox]: Get ready for SSD FW update tool

### PR DESCRIPTION
**Pull request by nazariig**
Signed-off-by: Nazarii Hnydyn nazariig@mellanox.com

Note: platform/mellanox/mlnx-ssd-fw-update.sh need to be replaced once the GA is available

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by nazariig** [comment]
@stephenxs / @stepanblyschak please review

**Comment by nazariig** [comment]
@stephenxs the motivation is get ready for SSD util + introduce some infra improvements

**Comment by nazariig** [comment]
@liat-grozovik please have a look

**Comment by stephenxs** [comment]
> @stephenxs Yes. The PR is ready for review. The motivation is get ready for SSD util + introduce some infra improvements

In this sense,  I suggest to re title in order to reflect what has been done in the PR better.

**Comment by nazariig** [comment]
> 
> 
> > @stephenxs Yes. The PR is ready for review. The motivation is get ready for SSD util + introduce some infra improvements
> 
> In this sense, I suggest to re title in order to reflect what has been done in the PR better, like `prepare for SSD fw update tool` or `improve the organizing of fw update tools`.
> How do you think?

Sure. Fixed.

**Pull request closed without merging**
